---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read the csv file

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```

Make a table with the file

```{r}
table(mxl$Genotype..forward.strand.)
```

Percentage of four catalogues in the whole sample number

```{r}
table(mxl$Genotype..forward.strand.) / nrow(mxl) * 100
```

To interpret base qualities for ASCII
Install the packages  

```{r}
#install.packages("seqinr")
#install.packages("gtools")
```



```{r}
library(seqinr)
library(gtools)
chars <- s2c("DDDDCDEDCDDDDBBDDDCC@")
chars
phred <- asc ( chars ) - 33
phred
```

Section 4

```{r}
rstable <- "rs8067378_ENSG00000172057.6.txt"
expr <- read.table(rstable)
head(expr)
```

```{r}
table(expr$geno)
```

Find the columns and rows of G/G

```{r}
inds.gg <- expr$geno == "G/G"
summary (expr[inds.gg, "exp"])
```

Find the columns and rows of G/G

```{r}
inds.ag <- expr$geno == "A/G"
summary (expr[inds.ag, "exp"])
```

Find the columns and rows of A/A

```{r}
inds.aa <- expr$geno == "A/A"
summary (expr[inds.aa, "exp"])
```

To make a boxplot

```{r}
boxplot(exp ~ geno, data = expr, notch = TRUE)
```

# Boxplot with the data shown


```{r}
library(ggplot2)

## Boxplot
ggplot(expr, aes(geno, exp)) + geom_boxplot()

ggplot(expr, aes(geno, exp, fill=geno)) + 
  geom_boxplot(notch=TRUE, outlier.shape = NA) + 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)
```